// Reads src/prompts/prompts.yaml and generates src/prompts/generated.ts.
// Run: node scripts/build-prompts.mjs (or via npm run build-prompts)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { load } from "js-yaml";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const yamlPath = join(root, "src/prompts/prompts.yaml");
const outPath  = join(root, "src/prompts/generated.ts");

const data = load(readFileSync(yamlPath, "utf-8"));

const ts = `// AUTO-GENERATED by scripts/build-prompts.mjs — DO NOT edit this file.
// Edit src/prompts/prompts.yaml and run: npm run build-prompts

/* eslint-disable */
// prettier-ignore
export const PROMPTS = ${JSON.stringify(data, null, 2)} as const;
`;

mkdirSync(join(root, "src/prompts"), { recursive: true });
writeFileSync(outPath, ts, "utf-8");
console.log("[build-prompts] ✓ src/prompts/generated.ts updated");
